-- ============================================
-- PHV Naturo - Fiches Pathologies
-- Basées sur les cours d'anatomie-physiologie
-- ============================================

-- ============================================
-- SYSTÈME DIGESTIF
-- ============================================

INSERT INTO fiches_pathologies (nom, systeme, description, causes, signes_cliniques, conseils_alimentation, aliments_eviter, aliments_privilegier, conseils_activite, conseils_stress, conseils_routine, complements, phytotherapie, aromatherapie, notes) VALUES

('Syndrome de l''intestin irritable (SII)', 'Digestif',
'Trouble fonctionnel intestinal chronique caractérisé par des douleurs abdominales et des troubles du transit. Affecte 10-15% de la population, majoritairement les femmes.',
'- Dysbiose intestinale\n- Perméabilité intestinale (leaky gut)\n- Stress chronique (axe intestin-cerveau)\n- Intolérances alimentaires (FODMAPs, gluten, lactose)\n- Post-infection (SII post-infectieux)\n- Déséquilibre du système nerveux entérique',
'- Douleurs abdominales soulagées par la défécation\n- Ballonnements et distension\n- Alternance diarrhée/constipation ou prédominance\n- Mucus dans les selles\n- Sensation d''évacuation incomplète\n- Fatigue associée',
'Alimentation pauvre en FODMAPs en phase d''éviction (4-6 semaines), puis réintroduction progressive. Mastication +++, repas calmes, fractionnés si besoin.',
'Oignon, ail, blé, seigle, lactose, légumineuses, pomme, poire, choux, édulcorants polyols, aliments ultra-transformés',
'Riz, quinoa, avoine sans gluten, carottes cuites, courgettes, banane mûre, myrtilles, poulet, poisson, œufs, huile olive, gingembre, fenouil',
'Activité douce régulière (marche, yoga, natation). Éviter sports intenses qui aggravent les symptômes. Le mouvement aide le transit.',
'Gestion du stress ESSENTIELLE (axe intestin-cerveau). Cohérence cardiaque 3x/jour, méditation, sophrologie. Le stress aggrave directement les symptômes.',
'- Manger assis, au calme, sans écran\n- Mastiquer longuement\n- Ne pas boire pendant les repas\n- Tenir un journal alimentaire\n- Horaires réguliers',
'- L-Glutamine 5g/jour (réparation muqueuse)\n- Probiotiques spécifiques SII (L. plantarum 299v)\n- Enzymes digestives\n- Magnésium si constipation',
'- Mélisse (antispasmodique, anxiolytique)\n- Menthe poivrée (si pas de RGO)\n- Fenouil (carminatif)\n- Camomille (anti-inflammatoire)',
'- HE Menthe poivrée en capsules gastrorésistantes\n- HE Basilic tropical (antispasmodique)\n- HE Estragon sur le ventre diluée',
'Toujours rechercher et traiter une dysbiose ou SIBO associé. Le SII nécessite une approche globale et de la patience (3-6 mois minimum).'),

('Reflux gastro-œsophagien (RGO)', 'Digestif',
'Remontée du contenu gastrique acide dans l''œsophage, causant brûlures et régurgitations. Peut évoluer vers œsophagite si chronique.',
'- Hypotonie du sphincter œsophagien inférieur\n- Hernie hiatale\n- Surpoids, obésité abdominale\n- Alimentation inadaptée\n- Stress (augmente l''acidité)\n- Helicobacter pylori\n- Médicaments (AINS, aspirine)',
'- Pyrosis (brûlures rétrosternales)\n- Régurgitations acides\n- Toux chronique nocturne\n- Enrouement matinal\n- Mauvaise haleine\n- Douleurs thoraciques (diagnostic différentiel cardiaque)',
'Repas légers le soir, 3h avant le coucher. Éviter de s''allonger après manger. Fractionner les repas. Ne pas boire pendant les repas.',
'Café, alcool, menthe, chocolat, agrumes, tomates, épices fortes, fritures, boissons gazeuses, aliments acides',
'Légumes cuits, riz, pomme de terre, banane, pomme cuite, poisson vapeur, viandes maigres, amandes (alcalinisantes), gingembre frais',
'Éviter les exercices qui augmentent la pression abdominale après les repas. Marche douce favorise la digestion.',
'Stress = augmentation acidité. Relaxation, respiration abdominale, gestion des émotions.',
'- Surélever la tête de lit (10-15 cm)\n- Ne pas se coucher juste après manger\n- Éviter vêtements serrés\n- Perdre du poids si surpoids',
'- Lithothamne ou argile blanche (tamponne acidité)\n- Aloe vera gel buvable\n- Glutamine (si œsophagite)\n- DGL (réglisse déglycyrrhizinée)',
'- Réglisse DGL (protège muqueuse)\n- Guimauve (émolliente)\n- Mélisse (si stress associé)\n- PAS de menthe (aggrave)',
'- HE Citron zeste (1 goutte dans miel, digestif)\n- Éviter HE Menthe poivrée (relâche le sphincter)',
'Attention: RGO chronique = risque œsophage de Barrett. Orienter vers gastro-entérologue si symptômes > 3 mois ou signes d''alarme.'),

('Constipation chronique', 'Digestif',
'Transit ralenti avec moins de 3 selles par semaine, selles dures et difficiles à évacuer. Très fréquent, surtout chez les femmes.',
'- Alimentation pauvre en fibres\n- Hydratation insuffisante\n- Sédentarité\n- Stress, anxiété\n- Dysbiose intestinale\n- Hypothyroïdie\n- Médicaments (opiacés, fer, antidépresseurs)\n- Ignorer le besoin d''aller à la selle',
'- Moins de 3 selles/semaine\n- Selles dures, en billes\n- Effort à la défécation\n- Sensation d''évacuation incomplète\n- Ballonnements\n- Douleurs abdominales',
'Augmenter progressivement les fibres (pour éviter ballonnements). Hydratation 1.5-2L/jour. Pruneaux, figues, graines de lin.',
'Riz blanc, banane pas mûre, carotte crue, chocolat, thé noir, aliments ultra-transformés',
'Légumes verts, légumineuses trempées, pruneaux, figues, graines de lin/chia trempées, kiwi, eau tiède citron matin, huile olive',
'Activité physique quotidienne ESSENTIELLE. La marche, le yoga (torsions) stimulent le péristaltisme.',
'Le stress contracte les intestins. Relaxation, ne pas se retenir d''aller aux toilettes.',
'- Verre d''eau tiède citronné au réveil\n- Respecter le réflexe gastro-colique après le petit-déjeuner\n- Position physiologique aux WC (marche-pied)\n- Horaire régulier',
'- Magnésium (citrate ou oxyde - effet laxatif)\n- Psyllium ou fibres d''acacia\n- Probiotiques (B. lactis)\n- Vitamine C haute dose',
'- Mauve, guimauve (mucilages)\n- Rhubarbe (à éviter au long cours)\n- Séné, bourdaine (ponctuellement)\n- Fenouil (carminatif)',
'- HE Gingembre (massage abdominal)\n- HE Estragon (antispasmodique)\n- Massage sens des aiguilles d''une montre',
'Attention aux laxatifs irritants (séné, bourdaine) : pas plus de 7-10 jours. Risque de dépendance et de "paresse" intestinale.'),

('Candidose digestive', 'Digestif',
'Prolifération excessive de Candida albicans dans le tube digestif, créant une dysbiose. Souvent sous-diagnostiquée.',
'- Antibiothérapies répétées\n- Alimentation riche en sucres\n- Immunodépression\n- Stress chronique\n- Contraception orale\n- Diabète\n- Corticothérapie',
'- Ballonnements après les repas\n- Envies de sucre irrépressibles\n- Fatigue chronique\n- Brouillard mental\n- Mycoses récidivantes (vaginales, cutanées)\n- Troubles de l''humeur\n- Langue blanche',
'Régime anti-candida strict pendant 4-8 semaines : sans sucres, sans levures, sans alcool, sans produits fermentés au début.',
'Sucres (tous), pain et levures, alcool, vinaigre, champignons, fromages fermentés, fruits (phase 1), lactose',
'Légumes verts, ail, oignon, coco, huile olive, protéines maigres, citron, avocat, œufs, herbes fraîches',
'Activité modérée. Le sport intense peut aggraver temporairement (die-off). Transpiration aide élimination.',
'Stress = immunodépression = prolifération candida. Gestion du stress indispensable.',
'- Éviter les sucres même "naturels" au début\n- Réintroduction très progressive des fruits\n- Cure de 2-3 mois minimum',
'- Probiotiques spécifiques (S. boulardii, L. rhamnosus)\n- Acide caprylique\n- Biotine\n- Extrait de pépins de pamplemousse',
'- Ail (antifongique puissant)\n- Berberine\n- Pau d''arco (Lapacho)\n- Origan',
'- HE Origan compact (antifongique majeur)\n- HE Tea tree\n- HE Cannelle écorce\n- EN CAPSULES GASTRORÉSISTANTES',
'Attention au die-off (réaction de Herxheimer) : maux de tête, fatigue, aggravation temporaire. Aller progressivement. Durée cure: 2-6 mois.'),

-- ============================================
-- SYSTÈME NERVEUX / STRESS
-- ============================================

('Stress chronique et épuisement', 'Nerveux',
'État de tension prolongée dépassant les capacités d''adaptation de l''organisme. Conduit à l''épuisement surrénalien si non traité.',
'- Surcharge professionnelle/personnelle\n- Manque de récupération\n- Alimentation inadaptée\n- Manque de sommeil\n- Perfectionnisme\n- Difficultés relationnelles\n- Événements de vie',
'- Fatigue persistante non soulagée par le repos\n- Troubles du sommeil\n- Irritabilité, anxiété\n- Difficultés de concentration\n- Douleurs musculaires, céphalées\n- Infections à répétition\n- Troubles digestifs',
'Alimentation régulière, riche en nutriments. Éviter le café qui épuise les surrénales. Protéines à chaque repas.',
'Café, sucres raffinés, alcool, aliments ultra-transformés, repas sautés',
'Protéines qualité, oméga-3, magnésium (chocolat noir, oléagineux), vitamines B (céréales complètes), légumes colorés',
'Activité physique MODÉRÉE. Éviter le sport intense qui épuise davantage. Yoga, marche, natation, qi gong.',
'PRIORITÉ ABSOLUE. Cohérence cardiaque, méditation, sophrologie, nature, limites personnelles, déconnexion.',
'- Coucher avant 22h30\n- Routines apaisantes\n- Pauses régulières\n- Respiration consciente\n- Limiter les écrans',
'- Magnésium bisglycinate 400mg/jour\n- Vitamines B complexe\n- Vitamine C (surrénales)\n- Oméga-3',
'- Rhodiola (adaptogène)\n- Ashwagandha (si anxiété)\n- Eleuthérocoque\n- Schisandra',
'- HE Épinette noire (surrénales) - sur les reins matin\n- HE Lavande vraie (calmante)\n- HE Petit grain bigarade',
'Le stress chronique est une urgence naturopathique. Orienter si signes de burn-out ou dépression. Travail sur les CAUSES.'),

('Insomnie et troubles du sommeil', 'Nerveux',
'Difficultés d''endormissement, réveils nocturnes ou réveil précoce affectant la qualité de vie. Touche 20-30% de la population.',
'- Stress, anxiété, ruminations\n- Mauvaise hygiène de sommeil\n- Écrans le soir (lumière bleue)\n- Caféine, excitants\n- Dérèglement circadien\n- Douleurs chroniques\n- Apnée du sommeil',
'- Difficulté d''endormissement > 30 min\n- Réveils nocturnes multiples\n- Réveil précoce\n- Sommeil non réparateur\n- Fatigue diurne\n- Irritabilité\n- Troubles de concentration',
'Dîner léger 3h avant coucher. Éviter alcool (perturbe sommeil profond). Tisanes relaxantes le soir.',
'Café/thé après 14h, alcool, repas lourds le soir, sucres rapides le soir, excitants',
'Glucides complexes le soir (favorisent sérotonine), tryptophane (dinde, banane, noix), magnésium, oméga-3',
'Activité physique régulière MAIS pas après 18h. Le matin ou en journée, aide à la fatigue physiologique.',
'Gestion des ruminations. Écrire ses préoccupations, cohérence cardiaque avant coucher, relaxation progressive.',
'- Horaires fixes coucher/lever\n- Chambre fraîche (18°C), obscure, silencieuse\n- Pas d''écrans 2h avant\n- Rituel de détente\n- Éviter siestes > 20 min',
'- Magnésium bisglycinate (soir)\n- L-Théanine (anxiété)\n- Mélatonine (jetlag, décalage)\n- GABA\n- Tryptophane ou 5-HTP',
'- Valériane + Passiflore + Houblon\n- Eschscholtzia (pavot Californie)\n- Mélisse (si stress digestif)\n- Tilleul, aubépine',
'- HE Lavande vraie (sur oreiller)\n- HE Petit grain bigarade\n- HE Camomille romaine\n- Diffusion chambre avant coucher',
'Rechercher apnée du sommeil si ronflement, surpoids, fatigue malgré sommeil suffisant. La mélatonine n''est pas un somnifère.'),

('Anxiété généralisée', 'Nerveux',
'Inquiétude excessive et persistante concernant divers aspects de la vie, difficile à contrôler, avec symptômes somatiques.',
'- Prédisposition génétique\n- Traumatismes\n- Stress chronique\n- Déséquilibre neurotransmetteurs (GABA, sérotonine)\n- Dysbiose intestinale (axe intestin-cerveau)\n- Carences (magnésium, B, oméga-3)\n- Hypoglycémies',
'- Inquiétude permanente disproportionnée\n- Tension musculaire\n- Troubles du sommeil\n- Irritabilité\n- Difficultés de concentration\n- Fatigue\n- Symptômes digestifs',
'Stabiliser la glycémie (IG bas). Éviter les excitants. Oméga-3 +++. Microbiote intestinal.',
'Café, sucres rapides, alcool, aliments ultra-transformés, édulcorants',
'Oméga-3 (poissons gras), magnésium, tryptophane, probiotiques, légumes verts, protéines régulières',
'Activité physique régulière : effet anxiolytique prouvé. Yoga, marche nature, natation.',
'Thérapie (TCC efficace), cohérence cardiaque 3x5min/jour, méditation pleine conscience, EFT.',
'- Limiter informations anxiogènes\n- Contacts sociaux positifs\n- Nature\n- Créativité\n- Respiration consciente',
'- Magnésium bisglycinate 400mg\n- Oméga-3 EPA/DHA 2g\n- L-Théanine 200mg\n- Probiotiques (axe intestin-cerveau)\n- Vitamines B',
'- Passiflore (anxiolytique)\n- Aubépine (palpitations)\n- Mélisse\n- Rhodiola (si épuisement)\n- Griffonia (5-HTP)',
'- HE Lavande vraie (inhalation, massage)\n- HE Ylang-ylang\n- HE Marjolaine à coquilles\n- HE Camomille romaine',
'Attention: Ne pas arrêter un traitement anxiolytique sans avis médical. La naturopathie accompagne, ne remplace pas un suivi psy si nécessaire.'),

-- ============================================
-- SYSTÈME IMMUNITAIRE
-- ============================================

('Infections ORL à répétition', 'Immunitaire',
'Rhumes, rhinopharyngites, otites, angines récidivants (plus de 4-6 épisodes/an). Fréquent chez l''enfant mais aussi l''adulte.',
'- Déficit immunitaire fonctionnel\n- Dysbiose intestinale (70% immunité)\n- Carences (D, zinc, fer, C)\n- Terrain allergique/inflammatoire\n- Stress chronique\n- Exposition collectivité\n- Tabagisme passif',
'- Rhinopharyngites répétées\n- Otites moyennes\n- Angines\n- Sinusites\n- Fatigue chronique\n- Ganglions fréquemment gonflés',
'Réduire les aliments pro-inflammatoires et mucogènes. Soutenir le microbiote intestinal.',
'Produits laitiers (mucogènes), sucres raffinés (immunodépresseurs), aliments ultra-transformés',
'Ail, oignon, thym, miel (local), propolis, champignons (shiitake), agrumes, kiwi, légumes colorés, bouillon os',
'Activité physique modérée (booste immunité). Éviter surmenage sportif (immunodépression).',
'Stress = cortisol = immunodépression. Gestion du stress, sommeil suffisant.',
'- Lavage nasal quotidien (eau salée)\n- Aérer les pièces\n- Humidifier si air sec\n- Éviter surchauffe des pièces',
'- Vitamine D3 2000-4000 UI/jour\n- Zinc 15-30mg\n- Vitamine C 500-1000mg\n- Probiotiques (L. rhamnosus)\n- Fer si carence',
'- Échinacée (3 sem max, pas si auto-immun)\n- Sureau\n- Thym\n- Propolis\n- Astragale (prévention)',
'- HE Ravintsara (antivirale++)\n- HE Tea tree\n- HE Eucalyptus radié (ORL)\n- HE Thym à linalol (enfants)',
'Chez l''enfant: vérifier végétations, allergies, reflux. Échinacée CI si maladie auto-immune. Cure préventive à partir de septembre.'),

('Allergies saisonnières (rhinite)', 'Immunitaire',
'Réaction excessive du système immunitaire aux pollens, avec symptômes ORL. Touche 20-30% de la population.',
'- Terrain atopique génétique\n- Dysbiose intestinale\n- Perméabilité intestinale\n- Surcharge hépatique\n- Pollution\n- Exposition précoce (théorie hygiéniste)',
'- Éternuements en salves\n- Rhinorrhée claire\n- Prurit nasal et oculaire\n- Congestion nasale\n- Larmoiement\n- Fatigue\n- Parfois asthme associé',
'Réduire les aliments histamino-libérateurs. Soutenir le foie. Commencer 2-3 mois AVANT la saison.',
'Alcool, fromages affinés, charcuterie, tomate, fraise, agrumes, chocolat, crustacés, blancs d''œufs',
'Oignon (quercétine), brocoli, pomme, légumes verts, oméga-3, curcuma, gingembre',
'Activité en extérieur limitée les jours de pic pollinique. Préférer le matin tôt.',
'Le stress aggrave les allergies (histamine). Relaxation, cohérence cardiaque.',
'- Rincer les cheveux le soir\n- Ne pas sécher le linge dehors\n- Fermer les fenêtres les jours venteux\n- Lunettes de soleil\n- Purificateur d''air',
'- Quercétine 500mg 2x/jour\n- Vitamine C (antihistaminique naturel)\n- Oméga-3\n- Probiotiques (L. rhamnosus, B. longum)\n- Œufs de caille (Ovomet)',
'- Plantain (antihistaminique)\n- Ortie (reminéralisant, anti-allergique)\n- Cassis (bourgeons - cortisone-like)\n- Desmodium (foie)',
'- HE Estragon (anti-allergique)\n- HE Camomille allemande\n- HE Tanaisie annuelle\n- En inhalation ou voie orale capsules',
'COMMENCER 2-3 MOIS AVANT LA SAISON. Une fois la crise installée, c''est plus difficile. Travailler le terrain de fond.'),

-- ============================================
-- SYSTÈME HORMONAL
-- ============================================

('Hypothyroïdie', 'Endocrinien',
'Insuffisance de production d''hormones thyroïdiennes, ralentissant le métabolisme. Touche surtout les femmes après 50 ans.',
'- Thyroïdite de Hashimoto (auto-immune - 90%)\n- Carence en iode, sélénium, zinc\n- Stress chronique (axe thyroïdien)\n- Perturbateurs endocriniens\n- Excès de soja, crucifères crus\n- Déficit en fer\n- Post-partum',
'- Fatigue, ralentissement\n- Frilosité\n- Prise de poids, difficulté à maigrir\n- Constipation\n- Peau sèche, cheveux cassants\n- Dépression, troubles cognitifs\n- Bradycardie',
'Éviter les goitrogènes crus en excès. Apporter iode, sélénium, zinc. Attention au soja si Hashimoto.',
'Soja en excès (isoflavones), crucifères CRU en grande quantité, gluten si Hashimoto (perméabilité)',
'Algues (iode), noix du Brésil (sélénium 2-3/jour), fruits de mer, poisson, œufs, protéines animales',
'Activité physique régulière malgré la fatigue. Aide le métabolisme. Commencer doucement.',
'Stress = frein sur la thyroïde. Relaxation, sommeil, gestion émotionnelle.',
'- Exposition lumière naturelle matin\n- Éviter perturbateurs endocriniens (plastiques, cosmétiques)\n- Filtrer l''eau',
'- Sélénium 200µg/jour (si Hashimoto)\n- Zinc 15mg\n- Iode (prudence si Hashimoto)\n- L-Tyrosine (précurseur)\n- Fer si carence',
'- Ashwagandha (adaptogène, soutien thyroïdien)\n- Guggul (si hypo sans Hashimoto)\n- Coleus forskohlii',
'- HE Myrte vert (régulatrice thyroïdienne)\n- HE Épinette noire\n- Application sur la thyroïde diluée',
'Si Hashimoto: travailler la perméabilité intestinale (lien auto-immunité). Ne jamais arrêter Levothyrox sans avis médical.'),

('Syndrome prémenstruel (SPM)', 'Endocrinien',
'Ensemble de symptômes physiques et psychiques survenant 7-10 jours avant les règles, disparaissant après. Touche 75% des femmes.',
'- Déséquilibre œstrogènes/progestérone (hyperœstrogénie relative)\n- Déficit en progestérone\n- Foie surchargé (mal détox œstrogènes)\n- Carences (magnésium, B6, calcium)\n- Stress (progestérone → cortisol)',
'- Irritabilité, sautes d''humeur\n- Anxiété, déprime\n- Rétention d''eau, gonflements\n- Tension mammaire\n- Fringales sucrées\n- Maux de tête\n- Troubles digestifs',
'Soutenir le foie (détox œstrogènes). Réduire sel et sucres en phase lutéale. Magnésium +++.',
'Alcool, caféine, sel, sucres raffinés, produits laitiers (en phase lutéale surtout)',
'Crucifères (détox œstrogènes), légumes verts, graines de lin, poissons gras, chocolat noir, banane',
'Activité physique régulière (endorphines, drainage). Adapter l''intensité selon les phases du cycle.',
'Stress consomme la progestérone. Relaxation en 2ème partie de cycle, sommeil suffisant.',
'- Écouter son corps selon les phases\n- Cycle féminin n''est pas linéaire\n- Se reposer davantage avant les règles',
'- Magnésium bisglycinate 300-400mg\n- Vitamine B6 50-100mg (ou P5P)\n- Huile d''onagre 1000-1500mg phase lutéale\n- Calcium 1000mg\n- Zinc',
'- Gattilier (Vitex) - le matin 3 mois mini\n- Alchémille (progestérone-like)\n- Achillée millefeuille\n- Chardon-Marie (foie)',
'- HE Sauge sclarée (œstrogène-like)\n- HE Ylang-ylang\n- HE Géranium rosat\n- Massage bas-ventre',
'Gattilier: commencer après les règles, attendre 3 cycles pour évaluer. Éviter si FIV ou traitement hormonal.'),

-- ============================================
-- SYSTÈME OSTÉO-ARTICULAIRE
-- ============================================

('Arthrose', 'Ostéo-articulaire',
'Dégénérescence du cartilage articulaire avec douleur et raideur. Première cause de handicap après 40 ans.',
'- Vieillissement naturel\n- Surpoids (pression articulaire)\n- Traumatismes antérieurs\n- Inflammation chronique silencieuse\n- Acidose tissulaire\n- Carences (silicium, collagène)\n- Génétique',
'- Douleur mécanique (à l''effort, soulagée au repos)\n- Raideur matinale < 30 min\n- Craquements articulaires\n- Déformation progressive\n- Perte de mobilité\n- Localisation: genoux, hanches, mains, colonne',
'Alimentation anti-inflammatoire +++. Alcalinisante. Réduire le surpoids. Curcuma quotidien.',
'Sucres raffinés, viande rouge en excès, charcuterie, fritures, alcool, solanacées (certains), produits laitiers',
'Curcuma + poivre noir, gingembre, oméga-3, légumes colorés, fruits rouges, bouillon d''os, collagène',
'Activité physique adaptée INDISPENSABLE. Natation, vélo, marche. Renforcement musculaire. Éviter impacts.',
'Stress = inflammation. Le repos total est contre-productif (atrophie). Activité douce.',
'- Maintenir le mouvement\n- Chaleur sur les articulations\n- Perte de poids si nécessaire\n- Ergonomie',
'- Curcuma (BCM-95) 500-1000mg\n- Oméga-3 2g EPA/DHA\n- Collagène type II 5-10g\n- Silicium organique\n- Glucosamine/Chondroïtine',
'- Harpagophytum (griffe du diable)\n- Cassis (bourgeons)\n- Reine-des-prés\n- Prêle, ortie (reminéralisants)',
'- HE Gaulthérie (anti-inflammatoire local)\n- HE Eucalyptus citronné\n- HE Romarin camphré\n- En massage avec huile végétale',
'Harpagophytum: CI si ulcère gastrique, lithiase biliaire. L''arthrose se gère mais ne se guérit pas. Approche au long cours.'),

-- ============================================
-- SYSTÈME TÉGUMENTAIRE (PEAU)
-- ============================================

('Acné adulte', 'Tégumentaire',
'Acné persistant ou apparaissant à l''âge adulte, souvent hormonale chez la femme. Impact psychologique important.',
'- Déséquilibre hormonal (androgènes)\n- Hyperinsulinisme (IG élevé)\n- Dysbiose intestinale\n- Foie surchargé\n- Produits cosmétiques comédogènes\n- Stress (cortisol → sébum)\n- Alimentation inadaptée',
'- Comédons, papules, pustules\n- Localisations: menton, mâchoire (hormonal), front, joues\n- Peau grasse\n- Cicatrices\n- Récidives menstruelles chez la femme',
'Alimentation IG bas stricte. Éviction produits laitiers (lien prouvé). Soutenir le foie et l''intestin.',
'Produits laitiers TOUS, sucres et IG élevé, charcuterie, aliments ultra-transformés, whey protéine',
'Légumes verts, zinc (graines de courge), oméga-3, curcuma, thé vert, aliments fermentés',
'Transpiration élimine toxines mais nettoyer après. Sport régulier bénéfique pour hormones et stress.',
'Stress = cortisol = sébum. Gestion du stress importante dans l''acné.',
'- Nettoyage doux (pas de décapage)\n- Cosmétiques non comédogènes\n- Ne pas toucher le visage\n- Changer taie d''oreiller régulièrement',
'- Zinc bisglycinate 30mg/jour\n- Oméga-3\n- Probiotiques (L. rhamnosus)\n- Bardane\n- Desmodium/Chardon-Marie (foie)',
'- Bardane (dépurative, anti-séborrhéique)\n- Pensée sauvage\n- Ortie racine (si androgènes)\n- Chardon-Marie (foie)',
'- HE Tea tree (local sur boutons)\n- HE Lavande vraie (cicatrisant)\n- HE Géranium rosat\n- DILUÉS dans huile végétale non comédogène',
'Patience: 3 mois minimum pour voir des résultats. Si traitement Roaccutane: pas de vitamine A haute dose. Bilan hormonal si acné sévère femme.'),

('Eczéma atopique', 'Tégumentaire',
'Dermatite chronique inflammatoire avec peau sèche et prurit intense. Terrain atopique familial (eczéma, asthme, allergies).',
'- Terrain atopique génétique\n- Altération de la barrière cutanée (filaggrine)\n- Dysbiose intestinale et cutanée\n- Allergènes (alimentaires, aéroportés)\n- Stress (facteur déclenchant majeur)\n- Xérose (peau sèche)',
'- Plaques rouges, sèches, prurigineuses\n- Localisations: plis (coudes, genoux), visage, mains\n- Peau très sèche\n- Suintement en phase aiguë\n- Lichénification si chronique\n- Troubles du sommeil',
'Rechercher les allergies/intolérances alimentaires. Soutenir la barrière intestinale. Oméga-6 (GLA).',
'Allergènes identifiés, produits laitiers (souvent en cause), gluten (à tester), histamino-libérateurs',
'Oméga-3, huile de bourrache/onagre, probiotiques, curcuma, légumes variés, bouillon d''os',
'Éviter transpiration excessive qui irrite. Sport en intérieur en période de pollens si atopique respiratoire.',
'Stress = poussée d''eczéma (prouvé). Gestion du stress, relaxation, travail émotionnel important.',
'- Émollients quotidiens (base végétale)\n- Bain tiède court\n- Vêtements coton\n- Lessive hypoallergénique\n- Ongles courts (grattage)',
'- Huile de bourrache ou onagre 1500mg (GLA)\n- Oméga-3 2g\n- Probiotiques (L. rhamnosus GG)\n- Zinc 15mg\n- Vitamine D',
'- Bardane (dépurative)\n- Pensée sauvage\n- Réglisse (anti-inflammatoire)\n- Desmodium (terrain allergique)',
'- HE Camomille allemande (anti-inflammatoire)\n- HE Lavande vraie\n- HE Hélichryse (cicatrisant)\n- Dans huile de calendula ou calophylle',
'Eczéma = signal d''alarme du corps. Travail de fond sur l''intestin et le stress. Éviter la cortisone au long cours si possible.'),

-- ============================================
-- SYSTÈME CARDIOVASCULAIRE
-- ============================================

('Hypertension artérielle', 'Cardiovasculaire',
'Élévation chronique de la pression artérielle (> 140/90 mmHg). Premier facteur de risque cardiovasculaire. Souvent silencieuse.',
'- Alimentation trop salée\n- Surpoids, sédentarité\n- Stress chronique\n- Alcool, tabac\n- Résistance à l''insuline\n- Apnée du sommeil\n- Génétique\n- Rigidité artérielle (âge)',
'- Souvent asymptomatique\n- Céphalées occipitales matinales\n- Vertiges\n- Acouphènes\n- Essoufflement\n- Saignements de nez',
'Régime DASH ou méditerranéen. Réduction drastique du sel. Potassium et magnésium +++.',
'Sel et produits salés (charcuterie, fromage, pain), réglisse, alcool, caféine en excès, sucres raffinés',
'Légumes riches en potassium (banane, avocat, épinards), ail, céleri, betterave, oméga-3, chocolat noir, graines',
'Activité physique régulière ESSENTIELLE. 30-45 min/jour. Aérobie: marche rapide, vélo, natation.',
'Stress = hypertension. Cohérence cardiaque 3x/jour (baisse prouvée), relaxation, sommeil.',
'- Perte de poids si surpoids\n- Arrêt tabac\n- Limiter alcool (1-2 verres max)\n- Automesure tensionnelle',
'- Magnésium 400mg\n- Oméga-3 3g\n- Coenzyme Q10 100-200mg\n- Potassium (alimentation)\n- Taurine',
'- Ail (vasodilatateur)\n- Olivier (feuilles)\n- Aubépine (régulateur cardiaque)\n- Hibiscus',
'- HE Ylang-ylang (hypotensive)\n- HE Lavande vraie\n- HE Marjolaine\n- En olfaction ou massage plexus',
'NE JAMAIS arrêter un traitement antihypertenseur sans avis médical. La naturopathie accompagne, permet parfois de réduire les doses.'),

('Hypercholestérolémie', 'Cardiovasculaire',
'Élévation du cholestérol sanguin, principalement du LDL-c. Facteur de risque cardiovasculaire à contextualiser.',
'- Alimentation riche en graisses saturées/trans\n- Sédentarité\n- Surpoids\n- Résistance à l''insuline\n- Hypothyroïdie\n- Génétique (hypercholestérolémie familiale)\n- Stress chronique',
'- Asymptomatique le plus souvent\n- Découverte fortuite sur bilan\n- Arc cornéen, xanthomes (formes sévères)\n- À contextualiser: ratio HDL/LDL, triglycérides, inflammation',
'Alimentation méditerranéenne. Fibres solubles +++. Phytostérols. Réduire les graisses saturées et trans.',
'Fritures, viennoiseries, charcuterie, beurre en excès, graisses trans (industriels), sucres (→ triglycérides)',
'Avoine (bêta-glucanes), légumineuses, noix, huile olive, poissons gras, ail, phytostérols (soja), pomme',
'Activité physique régulière augmente le HDL ("bon cholestérol"). 30-45 min/jour.',
'Stress chronique = augmentation cholestérol. Gestion du stress, relaxation.',
'- Perte de poids si surpoids\n- Arrêt tabac\n- Regarder le CONTEXTE global (inflammation, glycémie)',
'- Oméga-3 2-3g (surtout si triglycérides)\n- Berbérine (efficacité prouvée)\n- Levure de riz rouge (attention: équivalent statine)\n- Phytostérols\n- CoQ10 si statines',
'- Ail (hypolipémiant)\n- Artichaut (bile, cholestérol)\n- Olivier (feuilles)\n- Chrysanthellum',
'- HE Romarin verbénone (hépatoprotecteur)\n- HE Citron (détox hépatique)\n- HE Carotte (régénérant hépatique)',
'Levure de riz rouge = monacolline K = lovastatine naturelle. Mêmes précautions que statines. Ne pas associer.');

SELECT 'Fiches pathologies insérées avec succès!' AS message;
